### ISSUE TITLE
Please add license File.

### ISSUE THREAD

**Issue by jordwalke** [jpdeplaix/ocaml-monomorphic#3]
Would you be so kind as to select a license file?

**Comment by jpdeplaix** [comment]
There is already one selected here: https://github.com/jpdeplaix/ocaml-monomorphic/blob/master/_oasis#L6 and on the top of each source files.
But yes maybe a LICENSE file would be better. I'll add one. I'll also specify it in the opam file.

**Comment by jordwalke** [comment]
Thanks much!
